### PR TITLE
feat: enable CORS, chore: add trees to seed

### PR DESCRIPTION
**Pull request by Jaszkowic**
* chore(deps): Remove dead deps

---
* ci(auth0): Remove all traces of auth0
* ci(supabase): Use latest version of cli

---
* docs(API): Remove auth0 from docs

---
* test(content range): Adjust range to may rows
* test(content range): Use env SUPABASE_MAX_ROWS
* test(v2): Clean out all v2 code

---
- Seed with data_assets public bucket (#225) (8c3915b)
- chore: adapt tests (fb3c603)

---
- feat: add 25 trees of each artbot to seed.sql (872f776)
- feat: enable cors, read ACCESS_CONTROL_ALLOW_ORIGIN from env (#236) (7034496)
- feat: 25 trees of each artbot in seed.sql
- feat(API)!: Remove all v2 api routes

---
**BREAKING CHANGE:** This removes all auth0 code an v2 routes

### CODE REVIEW

**Comment by julizet** [comment]
tested & LGTM

**Comment by Jaszkowic** [comment]
@ff6347 ab in production?

**Comment by ff6347** [comment]
> @ff6347 ab in production?

Did you take a look at the staging deploy? Does everything work as expected? I'm ooo until Friday. So I can't jump in to fix stuff

**Comment by Jaszkowic** [comment]
@ff6347 staging looks fine, but we can wait until next week, no need to rush.

**Comment by ff6347** [comment]
Let us wait

**Comment by ff6347** [comment]
haha. It is Thursday again. @Jaszkowic We still have a ticket open to tighten the RLS rules. Should we wait until we also have these set up right and then do one big breaking change release?

**Comment by Jaszkowic** [comment]
Sure, let's wait some more. No benefits at this point to get this out quickly.

**Review by raphael-arce — APPROVED** [review]
ship it 🚢

**Pull request merged**
