### PR TITLE
feat: remove double confirm on email change

### PR DESCRIPTION
**Pull request by raphael-arce**

### CODE REVIEW

**Review by ff6347 — CHANGES_REQUESTED** [review]
Please merge into staging first

**Comment by raphael-arce** [comment]
my bad. overlooked the branch. will change 👍

**Comment by ff6347** [comment]
This also needs to be done manually on the staging instance and the production instance. These settings only affect the dev environment (I think)

**Comment by raphael-arce** [comment]
Yes, thanks for the heads up. I updated staging in the supabase admin panel.

**Review by ff6347 — APPROVED** [review]

**Pull request merged**
