### PR TITLE
feat(GDK-153): Implement watering crud by @joergreichert

### PR DESCRIPTION
**Pull request by vogelino**
This PR is a WIP. It bases on @joergreichert's original PR in Leipzig Gießt, which adds the ability for waterings to be modified and deleted.

### CODE REVIEW

**Comment by vogelino** [comment]
There are too many differences btw. the fork and our repo. I'm closing this PR in favour another branch `feat/GDK-153` where I will apply the changes manually.

**Comment by joergreichert** [comment]
Yes true, thus I've squashed all the changes in one commit, so it is easier for you, to see the changes: https://github.com/CodeforLeipzig/tsb-tree-api-now-express/commit/de4b4e591314c2d5315f2c743b265bce27566620  (despite that there might be some changes formatting changes contained, not related to the actual feature).

**Comment by joergreichert** [comment]
[0001-watering-delete-and-update.patch.txt](https://github.com/technologiestiftung/giessdenkiez-de-postgres-api/files/8512775/0001-watering-delete-and-update.patch.txt) created patch for that commit via `git format-patch -1 de4b4e591314c2d5315f2c743b265bce27566620`

**Comment by vogelino** [comment]
No problem @joergreichert. The way you prepared the commit makes it at least very easy to read and follow along. Thx for that!

**Pull request closed without merging**
