### PR TITLE
feat: allow anon to see all profiles

### PR DESCRIPTION
**Pull request by raphael-arce**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208527064533362

### CODE REVIEW

**Review by aeschi — DISMISSED** [review]
LGTM! 👍

**Review by Jaszkowic — CHANGES_REQUESTED** [review]
As discussed: For security purposes, it would be better to have a database function that checks for a given username if it already exists. That way, we do not expose this table (including all user ids and all profile names) to the public.

**Comment by raphael-arce** [comment]
@Jaszkowic could you have another look? thanks 🙏

**Review by Jaszkowic — APPROVED** [review]
LGTM

**Pull request merged**
